export const intro=[
"I’m a self-taught creative professional from Kenya with a passion for turning ideas into brands, digital experiences, creative advertisements, animations, and functional digital products that people can connect with.",
"My journey started with graphic design. Over time, my curiosity pushed me beyond Photoshop and Illustrator into web design, frontend development, web applications, digital marketing, creative advertising, and animation.",
"Today, I combine design, technology, motion, and storytelling to help businesses, organizations, and individuals build stronger brands and digital experiences."]
export const whatIDo=[
["Web Design & Development","modern, responsive websites and web applications designed around real business needs."],
["Branding & Visual Design","logos, brand identities, social media graphics, posters, flyers, thumbnails, and other visual assets."],
["Creative Advertising","engaging digital ads, promotional campaigns, social media creatives, and visual concepts designed to capture attention and communicate a message."],
["Animation & Motion Design","animated posters, promotional animations, motion graphics, social media content, and visual storytelling."],
["UI/UX Design","clean and intuitive digital interfaces that balance aesthetics with usability."],
["Digital Marketing & Creative Content","visual campaigns and digital content designed to help brands communicate and reach their audience."],
["Web Applications","functional digital platforms that solve specific problems, from business systems to customer-facing applications."]]
export const sections=[
["My Approach",["I believe good creative work is more than making something look beautiful.","It should communicate clearly, tell a story, solve a problem, create an experience, and serve a purpose.","Whether I'm designing a brand identity, creating a social media advertisement, animating a campaign, or building a web application, I think about how the final product will work for the people it's intended for."]],
["Design Meets Technology",["One of the things that defines my work is my ability to move between creative and technical thinking.","I can design a visual identity, create an advertising concept, bring that concept to life through animation, design a responsive interface, and build the actual web experience behind it.","This allows me to approach projects from multiple perspectives — as a designer, developer, animator, and creative strategist."]],
["The Journey",["I didn't take the traditional route into technology.","I taught myself through experimentation, online resources, personal projects, client work, and plenty of trial and error.","Every project has been part of the learning process.","From creating my first designs to working on websites, applications, brands, advertisements, animations, and digital platforms, I've continued to expand my skills and challenge myself to build better things.","And I'm still learning."]],
["What I'm Building",["Through my work and Royal Graphix, I'm building a creative technology studio focused on helping businesses and organizations turn ideas into meaningful brands, digital products, advertisements, and experiences.","I'm particularly interested in projects where design, technology, advertising, animation, and business come together — whether that means creating a brand from scratch, developing a website, building a web application, producing a creative ad, or bringing a campaign to life through motion."]],
["Beyond the Screen",["For me, creativity isn't limited to a computer.","I love content and I recently started showcasing my work through content.","I'm interested in people, ideas, business, technology, storytelling, and the impact that good creative work can have on communities.","I enjoy collaborating with people who have an idea and helping them turn that idea into something real, engaging, and memorable."]]]
